### PR TITLE
Update license with up-to-date year

### PR DESCRIPTION
**Pull request by fay-jai**
Only made 1 change:
1) Update LICENSE to include the latest year in the form of a date-range.

No other changes were made.

### CODE REVIEW

**Comment by jakubroztocil** [comment]
Thanks @fay-jai. Does a date-range have any benefits over a single date? AFAIK when only one year is included, then it's implied that it's until `$NOW`.

**Comment by fay-jai** [comment]
To be honest, I'm basing this off of what I've seen on other large scale projects. It seems like the standard protocol which is why I suggested the change as well!

**Comment by leesei** [comment]
A date range can indicate when the content was first published and when it was last modified.
That has to do with counting years for copyright expiration.

**Comment by jakubroztocil** [comment]
Ok, thanks :+1:

**Pull request merged**
