### PR TITLE
tox.ini: Use pytest-httpbin>=0.0.6

### LINKED ISSUE #308: Failing tests in test_ssl.py
There are some failing test in [`test_ssl.py`](https://github.com/jakubroztocil/httpie/blob/master/tests/test_ssl.py). 

All the failures seem to be caused by some SSL-related issue `pytest-httpbin` as they only occur when the `httpbin_secure` fixture is used.

The HTTPS connection times out on Python3 and Pypy: 

* https://travis-ci.org/jakubroztocil/httpie/jobs/49870580
* https://travis-ci.org/jakubroztocil/httpie/jobs/49870583#L394

I can reproduce the timeouts also when running the test via `py.test …` from terminal even on Python 2.7.9, but strangely enough, they don't occur when the test suite is being run from PyCharm.

// cc @kevin1024, @msabramo

### PR DESCRIPTION
**Pull request by msabramo**
This hopefully fixes SSL timeout errors. 

Fixes #308

Cc: @jakubroztocil, @kevin1024

### CODE REVIEW

**Comment by kevin1024** [comment]
Nice.  Need to revert 985f65ef52991796afeb41be146605d7a1c8ed48 as well.

**Comment by msabramo** [comment]
> Nice. Need to revert 985f65e as well.

Thanks for the reminder! Done. And tests still passing. Great work, @kevin1024!

**Comment by jakubroztocil** [comment]
Excellent, thanks for the fixes @kevin1024 and @msabramo :+1:

**Comment by kevin1024** [comment]
No problem. Glad it worked!

**Pull request merged**
