### PR TITLE
Mark test_session_unicode as xfail

### PR DESCRIPTION
**Pull request by msabramo**
There are known problems with unicode in headers

### CODE REVIEW

**Comment by msabramo** [comment]
Related: https://github.com/jakubroztocil/httpie/issues/282

**Comment by jakubroztocil** [comment]
Looking at the documentation for [`pytest.mark.xfail`](http://pytest.org/latest/skipping.html#mark-a-test-function-as-expected-to-fail), it appears to me that when this decorator is used, then the test is expected to fail *every time*:

> This test will be run but no traceback will be reported when it fails. Instead terminal reporting will list it in the “expected to fail” or **“unexpectedly passing” sections**.

The problem we're having though is that it only fails *sometimes*, and when it does, we want to ignore the failure. But when it passes, it shouldn't be treated as an unexpected event.
 
I'd say marking it with `pytest.mark.skip` for Py3k (with a message linking to #282) might be the best option until the root cause is fixed.

**Comment by jakubroztocil** [comment]
Also, I see `pypy` and `pypy3` have been removed — why?

**Comment by msabramo** [comment]
Updated to use `pytest.mark.skipif` and I put `pypy` and `pypy3` back since that is a separate issue (you're right about why I removed them).

**Comment by jakubroztocil** [comment]
Great, thanks!

**Pull request merged**
