### PR TITLE
.travis.yml: sudo false for Docker containers

### PR DESCRIPTION
**Pull request by msabramo**
Enables new Docker container infrastructure.

### CODE REVIEW

**Comment by msabramo** [comment]
Hmmm, pypy and pypy3 timed out.

**Comment by jakubroztocil** [comment]
Thanks!

The timeout is related to #308.

**Comment by jakubroztocil** [comment]
That's a pretty cool feature btw. I'm wondering if the [caching](http://docs.travis-ci.com/user/caching/) this change enables works for `pip` packages as well.

**Comment by msabramo** [comment]
Yeah I haven't tried the caching yet. On other projects, usually just setting this speeds up the builds a bit though. It might be interesting to cache necessary wheels.

**Pull request merged**
