### PR TITLE
Add XDG_CONFIG_HOME support.

### PR DESCRIPTION
**Pull request by Yamakaky**
On Linux and Mac, the default config directory is now "~/.config/httpie" instead
of "~/.httpie". Fixes https://github.com/jkbrzt/httpie/issues/145

### CODE REVIEW

**Comment by Earnestly** [comment]
Make sure the path in `XDG_CONFIG_HOME` when set is absolute.  I.e. `XDG_CONFIG_HOME[0] == '/'`

**Comment by Yamakaky** [comment]
If it's not, then issue an error?

**Comment by Earnestly** [comment]
*Full disclaimer: I don't care about strict adherence and would rather something instead of nothing, so for example I don't care about people implementing support for `XDG_CONFIG_DIRS` until it actually matters, because usually it doesn't.*

As to your question, if the path set in `XDG_CONFIG_HOME` isn't absolute then you should use the fallback `HOME/.config`.

**Comment by Yamakaky** [comment]
Done !

**Comment by jleclanche** [comment]
@jkbrzt Hey, any blocker to merge this? It looks good.

**Comment by skmlcd** [comment]
Any progress?

**Comment by Earnestly** [comment]
Three months later, any news?

**Comment by skmlcd** [comment]
@jkbrzt ?

**Comment by Siilwyn** [comment]
@jakubroztocil thoughts?

Would love if this gets merged, my home directory would be thankful.

**Comment by jleclanche** [comment]
@jakubroztocil Will this be merged? Will this not be merged? Can I help land it?

**Comment by Siilwyn** [comment]
:point_up: same questions, if I can help by testing this locally or something else please let me know!

**Comment by jleclanche** [comment]
@jakubroztocil ping - see above

**Comment by aaronmehar** [comment]
@jakubroztocil Any plans to merge this at some point?

**Comment by neersighted** [comment]
I would also like to see this merged. @jakubroztocil, do you have any opposition to merging as-is?

**Comment by jakubroztocil** [comment]
The problem with this patch is that it changes the default config location without taking into account existing installations — people would end up with two config files one of them being be ignored (extremely bad user experience). It also assumes the existence of `~/.config/`. 

̉For this to be mergeable, it would need to:

* provide a "notify & migrate" mechanism for existing users
* have tests
* update the docs

**Comment by jleclanche** [comment]
> provide a "notify & migrate" mechanism for existing users

Can just attempt to read ~/.httpie first and move it automatically if it exists right?

**Comment by neersighted** [comment]
Ah, I didn't notice the lack of legacy support. I would just add another branch to the if tree, before the end, that checks if `~/.httpie` exists and just short-circuits the logic to use that folder.

**Pull request closed without merging**
