### PR TITLE
Feature/streamed uploads

### PR DESCRIPTION
**Pull request by myvcc657**
Bantu saya untuk setup `config`

### CODE REVIEW

**Comment by figure0** [comment]
httpie/cli.py
httpie/input.py
httpie/utils.py
tests/test_auth.py
tests/test_binary.py
tests/test_cli.py
tests/test_httpie.py
tests/test_uploads.py

**Comment by figure0** [comment]
httpie/cli.py
httpie/input.py
httpie/utils.py
tests/test_auth.py
tests/test_binary.py
tests/test_cli.py
tests/test_httpie.py
tests/test_uploads.py

**Comment by figure0** [comment]
Fonctionnalités / téléchargements en streaming # 624

**Comment by fty48jj19** [comment]
ok  vou pedir mas codigos para inimizar essa situaçao

**Pull request closed without merging**
