### PR TITLE
Follow terminal ANSI color styles

### PR DESCRIPTION
**Pull request by dsego**
Removes the default solarized color scheme and custom http lexer class.

### CODE REVIEW

**Comment by jakubroztocil** [comment]
Thanks, @dsego!

I've tested it with a couple of color schemes in iTerm and the vanilla `TerminalFormatter` seems to work quite well. Colored terminal output is generally tricky, though, so It will require more extensive testing on different platforms/configurations before this can become the new default. 

So instead of making it the default behaviour now, I'd go for a transitional period when this formatter is available only via an extra style option: `--style=native`.

As for the `Solarized` style, I'd keep it around — it's quite popular and removing it would break  backward compatibility (hopefully it will be included in Pygments one day).

Also, what were your thoughts behind removing the custom HTTP lexer? It provides a nicer formatting for HTTP headers than the default one so unless there's a good reason, let's keep it as well. 

Context: #524

**Comment by dsego** [comment]
Hey, thanks for the review @jakubroztocil. 

I agree it might be best to have it  is as an extra style option. 
As for the custom lexer, I found that the one included with pygments does really well with the vanilla `TerminalFormatter`,  http headers show in nice colors with good contrast. 

Here is a comparison of the default & custom lexer with [Snazzy theme](https://github.com/sindresorhus/iterm2-snazzy) in iTerm2:

headers

It may be the case that some color schemes supplied with pygments are not handling http headers nicely (monokai works well for example), so I agree with keeping the custom lexer.

**Comment by jakubroztocil** [comment]
The Snazzy theme looks great  :) 

> It may be the case that some color schemes supplied with pygments are not handling http headers nicely (monokai works well for example), so I agree with keeping the custom lexer.

We could also simply not apply the custom HTTP lexer when the "native" theme is active.

**Comment by dsego** [comment]
Since _native_ and _default_ are taken what do you think about one of the following:
_profile_, _auto_, _preset_, _local_, _terminal_, _term_, _scheme_?

**Comment by jakubroztocil** [comment]
Thanks, @dsego! I'll polish it a bit and it include in the next release.

**Comment by 9mm** [comment]
@dsego what font is that in your screenshot?

**Comment by dsego** [comment]
@9mm I believe this was roboto mono.

**Comment by 9mm** [comment]
Awesome thanks. How did you get those colors to appear like that? I installed the iterm2 theme and every --style option I try looks horrible. I'm thinking of making my own but not sure how

**Comment by dsego** [comment]
@9mm You may want to check out this issue https://github.com/jakubroztocil/httpie/issues/524.

**Comment by 9mm** [comment]
Oh I see. Thank you. What might be the best way to change this if I use homebrew and a new update will just clobber it?

**Comment by dsego** [comment]
@9mm The code in this PR is already merged in. So the next release should probably have an additional _--style_ option to match the colors to whatever iTerm2's color scheme is. When and how that happens is left to be seen.

**Comment by 9mm** [comment]
Cool, thanks for explaining

**Comment by ThiefMaster** [comment]
This change is bad :(

I use the default colors in the terminal and this is fine for pretty much everything - but now HTTPie uses an awful dark blue (on the black background almost everyone has in their terminal) for some parts, which is very hard to read.

Is there some global config file I can create to get back the old style? (and no, I don't want to use shell aliases for that)

**Comment by jakubroztocil** [comment]
You select the old default colors (< v1.0.0)  with `--style=solarized`.  To make it permanent, add it to `default_options` in your confit file. https://httpie.org/doc#config

**Pull request merged**
