### PR TITLE
Windows setup

### LINKED ISSUE #940: Add setup instructions for windows
As I have tried to setup my development environment for HTTPie on a Windows machine, I wasn't able to run the ``make`` command even after installing some third-party software. It would be great to add specific steps for windows setup. I discussed this with @jakubroztocil and he confirmed the issue.

Current guidelines provided for setup are located in [CONTRIBUTING.rst](https://github.com/jakubroztocil/httpie/blob/master/CONTRIBUTING.rst)

I will work on this since I have already identified the steps needed for windows setup.

### PR DESCRIPTION
**Pull request by ovezovs**
Fixes #940

### CODE REVIEW

**Comment by ovezovs** [comment]
@jakubroztocil, please let me know what you think. Also, I have asked someone who uses windows to test and review.

**Comment by jakubroztocil** [comment]
Do you think you could prefix the new _"If you are on a Windows machine and not able to run make"_ fallback section with one describing the standard Windows procedure of getting make etc., so that the standard instructions could be followed if successful?

**Comment by ovezovs** [comment]
I am still waiting on somebody else getting the instructions tested

**Comment by jakubroztocil** [comment]
🥳

**Pull request merged**
